### ISSUE TITLE
Link to Wiki not working.

### ISSUE THREAD

**Issue by PattyDePuh** [clint-tseng/awesomecomplete#18]
Greetings!

The path of the link to open the wiki page (inside the "Quick Start" section of file README.textile) seems not to work:
https://wiki.github.com/clint-tseng/Awesomecomplete

The server url responds to me with "Malformed request".
_We didn't receive a proper request from your browser. Please contact us if the problem persists._

Would you mind to fix that, if possible?
Thanks in advance!

**Comment by issa-tseng** [comment]
oops! i'm sorry. that should all be fixed now. thanks!
